"""
Convert raw script into structured editing plan (JSON).
Uses Gemini to generate context-aware B-roll suggestions aligned to the script.
"""
import json
from pathlib import Path

from .generate_script import load_prompt
from .llm import gemini_json, style_guide_text, load_references


def script_to_editing_plan(script: str, project_dir: Path | None = None) -> dict:
    """
    Call Gemini to produce an editing plan with script-aligned beats.
    Each broll beat has a suggestion in Subject/Camera/Scene format.
    Falls back to a simple all-aroll plan if the LLM call fails.
    """
    from core.user_brand import brand_context_text, load_user_brand, owner_id_from_project

    owner = owner_id_from_project(project_dir)
    brand_ctx = brand_context_text(load_user_brand(owner))
    base_prompt = load_prompt("editing_plan", script=script, brand_context=brand_ctx)

    refs = load_references("visual-patterns", "writing-styles")
    if refs:
        base_prompt += f"\n\n## Reference Material (follow these editing rules)\n\n{refs}\n"

    style_section = style_guide_text(project_dir)
    if style_section:
        base_prompt += f"\n\n{style_section}\n"

    base_prompt += (
        "\n## B-roll Suggestion Format\n"
        "Every broll suggestion MUST follow this structure:\n"
        "\"[Subject performing an action]. Camera: [one clear camera move]. "
        "[Scene/lighting/environment detail].\"\n"
        "Example: \"A hand writing in a planner with a pen. "
        "Camera: slow dolly-in. Warm morning light on a wooden desk.\"\n"
    )

    try:
        plan = gemini_json(base_prompt)
        if "beats" not in plan or not isinstance(plan["beats"], list):
            raise ValueError("LLM response missing 'beats' list")
        for beat in plan["beats"]:
            if "type" not in beat:
                raise ValueError(f"Beat missing 'type': {beat}")
        _enforce_aroll_start(plan)
        print("[OK] Editing plan generated by Gemini")
        return plan
    except Exception as e:
        from core.config import allow_placeholders

        if allow_placeholders():
            print(f"[WARN] Gemini editing plan failed ({e}), using fallback")
            return _fallback_plan()
        raise RuntimeError(f"Editing plan failed: {e}") from e


def _enforce_aroll_start(plan: dict) -> None:
    """Ensure the first beat is always aroll (speaker hook)."""
    beats = plan.get("beats", [])
    if not beats:
        return
    first = beats[0]
    if first.get("type") != "aroll":
        aroll_end = min(4, float(first.get("end_seconds", first.get("end", 4))))
        beats.insert(0, {
            "type": "aroll",
            "start": 0,
            "end_seconds": aroll_end,
            "suggestion": "",
        })
        first["start"] = aroll_end


def _fallback_plan() -> dict:
    """Simple all-aroll plan so the pipeline always runs."""
    return {
        "hook": {"start": 0, "end_seconds": 3, "note": "speaker face-to-camera hook"},
        "beats": [
            {"type": "aroll", "start": 0, "end_seconds": 30, "suggestion": ""},
        ],
        "total_duration_seconds": 30,
    }


def save_editing_plan(project_dir: Path, plan: dict) -> Path:
    out = project_dir / "final_script.json"
    out.write_text(json.dumps(plan, indent=2), encoding="utf-8")
    return out
