"""
Generate short-form video script from topic.txt using Gemini.
Uses prompts/ templates and the shared LLM client.
"""
from pathlib import Path


def load_prompt(name: str, **kwargs) -> str:
    path = Path(__file__).resolve().parent.parent / "prompts" / f"{name}.txt"
    text = path.read_text(encoding="utf-8")
    for key, value in kwargs.items():
        text = text.replace("{" + key + "}", str(value))
    return text


def generate_script(topic: str, project_dir: Path | None = None) -> str:
    """Generate a short-form video script via Gemini. Falls back to placeholder."""
    from .llm import gemini_text, style_guide_text, load_references

    base_prompt = load_prompt("script_generation", topic=topic)

    refs = load_references("hook-patterns", "writing-styles", "viral-angles")
    if refs:
        base_prompt += f"\n\n## Reference Material (follow these closely)\n\n{refs}\n"

    style_section = style_guide_text(project_dir)
    if style_section:
        base_prompt += f"\n\n{style_section}\n"

    try:
        script = gemini_text(base_prompt)
        print("[OK] Script generated by Gemini")
        return script
    except Exception as e:
        print(f"[WARN] Gemini script generation failed ({e}), using placeholder")
        return f"# Script draft\n\nTopic: {topic}\n\n[Replace with LLM-generated script.]"


if __name__ == "__main__":
    import sys
    topic_path = sys.argv[1] if len(sys.argv) > 1 else None
    if topic_path:
        topic = Path(topic_path).read_text(encoding="utf-8").strip()
    else:
        topic = "How to get more done in less time"
    print(generate_script(topic))
